CREATE TABLE jogo(
    id number generated by default as identity,
    nome varchar(100),
    plataforma varchar(100),
    genero varchar(50),
    classificacao number,
    desenvolvedor varchar(50),
    primary key(id)
);

alter table jogo rename column classificacao_etaria to classificacao;