create table tr_conta(
    id number generated by default as identity,
    numero varchar(15),
    agencia varchar(10),
    cliente varchar(40),
    saldo number(8, 2),
    primary key (id)
);

create table tr_lancamento(
    id number generated by default as identity,
    observacao varchar(80),
    tipo varchar(50),
    data date,
    valor number(8, 2),
    conta_id number,
    primary key(id),
    foreign key(conta_id) references tr_conta(id)
);

insert into tr_conta(numero, agencia, cliente, saldo) 
values('0001', '234', 'Vanderlei Cruz', 4500.00);

insert into tr_conta(numero, agencia, cliente, saldo) 
values('0005', '234', 'Odete Menezes', 1850.00);

insert into tr_conta(numero, agencia, cliente, saldo) 
values('0008', '234', 'Fernando Gomes', 13890.00);

insert into tr_conta(numero, agencia, cliente, saldo) 
values('0035', '234', 'Carla Brasil', 6840.00);
